---
title: "Jason Lessels"
author: "54 Merkland Rd East, Aberdeen AB24 5PZ, UK"
date: "+44 7803740363"
output:
  pdf_document:
    toc: no
  knitr:::html_vignette:
    number_sections: no
    toc: no
vignette: |
  %\VignetteIndexEntry{An introduction to Jason Lessels}
  %\VignetteEngine{knitr::rmarkdown_notangle}
  
---


```{r, eval = FALSE}
# To install and reproduce this resume use:
library(devtools)
install_github("johnDorian/jasonlessels")
library(jasonlessels)
# And now load this resume
vignette(topic = "resume", package = "jasonlessels")
# For more information...
help(package = jasonlessels)
# Now for the actual resume...
```

```{r, echo = FALSE, include=FALSE}
library(jasonlessels)

```



```{r, results='asis', echo=TRUE}
Employment()

```



```{r, results='asis'}
Education()
```



```{r, results='asis'}
Software_and_programming_languages()
```


```{r, results='asis'}
R_packages()
```


```{r, results='asis'}
Selected_papers_and_conferences()
```


```{r, results='asis'}
Interests_and_hobbies()
```


```{r, results='asis'}
Referees()
```
